function find_iris_slit_pos_new, coordarray, iris_xy_pos, indarray

;;;INPUT:
;
;coordarray = 1D array containing coordinates in arcseconds
;iris_xy_pos = 1D array containing slit locations in arcseconds generated by d->getxpos or d->getypos
;
;;;OUTPUT:
;indarray = an array containing the relevent indices for the slit position closest to the user defined coordarray

;find array sizes
nc = n_elements(coordarray)
nf = n_elements(iris_xy_pos[0, *])


;define output 2D array 
indarray = fltarr(nc, nf)

;loop through each coord in coordarray
for j = 0, nc - 1 do begin
    ;loop through each time step finding the closest slit position to coordarray[j]
    for i = 0, nf - 1 do begin
        a = abs(iris_xy_pos[*, i] - coordarray[j])
        mina = min(a, ind)
;        indarray[j, i] = array_indices(a, ind)
        indarray[j, i] = ind
    endfor
endfor
return, indarray
end

